---
- name: "Set target directory based on ctx.type"
  set_fact:
    target_dir: "{{ 'cn' if ctx.type == 'cn' else ('scn' if ctx.type == 'scn' else '') }}"

- name: "Check nodekey exists"
  stat:
    path: "{{ homi_output_dir }}/{{ ctx.type }}/keys"
  register: check_nodekey_file
  when:
  - ctx.num > 0

- name: "Generate {{ ctx.type }} data & genesis.json by Homi"
  shell: |
    {{ homi_bin }} setup {{ homi_default_options }} {{ homi_extra_options }} --test-num {{ homi_test_account_num }} --cn-num {{ ctx.num }} --chainID {{ kaia_network_id }} --network-id {{ kaia_network_id }} -o {{ homi_output_dir }}/{{ ctx.type }} local
  tags:
  - localhost
  when:
  - ctx.num > 0
  - check_nodekey_file.stat.exists == False

- name: "Create target directory if it doesn't exist"
  file:
    path: "{{ homi_output_dir }}/{{ target_dir }}/scripts"
    state: directory
    mode: '0755'
  when:
  - genesis_path is defined and genesis_path != ''
  - target_dir != ''

- name: "Replace genesis.json with existing one if genesis_path is provided"
  copy:
    src: "{{ genesis_path }}"
    dest: "{{ homi_output_dir }}/{{ target_dir }}/scripts/genesis.json"
  when:
  - genesis_path is defined and genesis_path != ''
  - target_dir != ''

- name: Convert and get validator data
  kaia_validator:
    homi_output_dir: "{{ homi_output_dir }}"
    node_type: "{{ ctx.type }}"
    node_index: "{{ node_index | int }}"
    port: "{{ kaia_port }}"
    public_ip: "{{ hostvars[item]['ansible_host'] }}"
    private_ip: "{{ hostvars[item]['ansible_private_host'] }}"
  register: validator_result
  loop: "{{ groups[ctx.type] }}"
  loop_control:
    index_var: node_index
  when:
  - ctx.num > 0

- name: Generate validator file
  copy:
    content: "{{ item.validator }}"
    dest: "{{ homi_output_dir }}/{{ ctx.type }}/keys/validator{{ node_index | int + 1 }}"
  loop: "{{ validator_result.results }}"
  loop_control:
    index_var: node_index
  when:
  - ctx.num > 0
