---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ cache_dir }}"
    - "{{ homi_output_dir }}"
    - "{{ kaia_build_dir }}"
  tags:
  - localhost

- name: Start to download dependencies
  include_tasks: download_dependency.yml
  tags:
  - localhost

- name: Start to download a package Linux
  include_tasks: download_package_linux.yml
  loop:
  - kgen
  - homi
  loop_control:
    loop_var: package_name
  tags:
  - localhost
  when:
  - ansible_system == "Linux"
  - kaia_install_mode == "package"

- name: Build kaia binaries
  include_role:
    name: build
  when:
  - kaia_install_mode in ["build", "build_remote"]
  tags:
  - localhost
  
- name: Start to download a package Darwin
  include_tasks: download_package_darwin.yml
  loop:
  - kgen
  - homi
  loop_control:
    loop_var: package_name
  tags:
  - localhost
  when:
  - ansible_system == "Darwin"
  - kaia_install_mode == "package"


- name: Generate genesis.json & nodekey & validator
  include_tasks: genesis.yml
  with_items:
  - { type: "cn", num: "{{ kaia_num_cn }}", network_id: "{{ kaia_network_id }}", chain_id: "{{ kaia_chain_id }}" }
  - { type: "pn", num: "{{ kaia_num_pn }}", network_id: "{{ kaia_network_id }}", chain_id: "{{ kaia_chain_id }}"  }
  - { type: "en", num: "{{ kaia_num_en }}", network_id: "{{ kaia_network_id }}", chain_id: "{{ kaia_chain_id }}"  }
  - { type: "scn", num: "{{ kaia_num_scn }}", network_id: "{{ kaia_service_network_id }}", chain_id: "{{ kaia_service_chain_id }}"  }
  - { type: "spn", num: "{{ kaia_num_spn }}", network_id: "{{ kaia_service_network_id }}", chain_id: "{{ kaia_service_chain_id }}"  }
  - { type: "sen", num: "{{ kaia_num_sen }}", network_id: "{{ kaia_service_network_id }}", chain_id: "{{ kaia_service_chain_id }}"  }
  loop_control:
    loop_var: ctx
  when:
  - kaia_network is none
  tags:
  - localhost

- name: Generate static-nodes.json
  include_tasks: static_nodes.yml
  with_items:
  - { is_service_chain: False, num_cn: "{{ kaia_num_cn }}", num_pn: "{{ kaia_num_pn }}", num_en: "{{ kaia_num_en }}" }
  - { is_service_chain: True, num_cn: "{{ kaia_num_scn }}", num_pn: "{{ kaia_num_spn }}", num_en: "{{ kaia_num_sen }}" }
  loop_control:
    loop_var: ctx
  when:
  - kaia_network is none
  tags:
  - localhost

- name: Generate main-bridges.json
  include_tasks: main_bridges.yml
  tags:
  - localhost
